Parsing SPARK's PAG file spark-dacapo/jre16/antlr-pag-nst ...
@timer 1: 1.3018
ParsePAG info: 
-------------------------------------------------
1219311 & 24494 & 822366 & 12892 & 41750 \\
	[DONE] 
the initial worklist size : 0
SCC and topological sorting ...
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
Propagation time       : 16.5415 s.
Propagation iterations : 18
Points-to size         : 90632939
Points-to set time     : 0.338948 s.
Total time             : 19.473 s.
Peak memory            : 1472.67 MB.
Parsing SPARK's PAG file spark-dacapo/jre16/bloat-pag-nst ...
@timer 1: 0.659899
ParsePAG info: 
-------------------------------------------------
642036 & 12050 & 462672 & 5750 & 17457 \\
	[DONE] 
the initial worklist size : 0
SCC and topological sorting ...
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
Propagation time       : 4.80927 s.
Propagation iterations : 14
Points-to size         : 25330002
Points-to set time     : 0.127981 s.
Total time             : 6.07208 s.
Peak memory            : 595.488 MB.
Parsing SPARK's PAG file spark-dacapo/jre16/chart-pag-nst ...
@timer 1: 1.61575
ParsePAG info: 
-------------------------------------------------
1556269 & 28202 & 1104768 & 14605 & 46249 \\
	[DONE] 
the initial worklist size : 0
SCC and topological sorting ...
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
Propagation time       : 26.8119 s.
Propagation iterations : 18
Points-to size         : 123364368
Points-to set time     : 0.437934 s.
Total time             : 30.5933 s.
Peak memory            : 1857.79 MB.
Parsing SPARK's PAG file spark-dacapo/jre16/eclipse-pag-nst ...
@timer 1: 0.558915
ParsePAG info: 
-------------------------------------------------
507881 & 11957 & 332096 & 5835 & 17059 \\
	[DONE] 
the initial worklist size : 0
SCC and topological sorting ...
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
Propagation time       : 4.22836 s.
Propagation iterations : 14
Points-to size         : 23626166
Points-to set time     : 0.120982 s.
Total time             : 5.30419 s.
Peak memory            : 566.914 MB.
Parsing SPARK's PAG file spark-dacapo/jre16/fop-pag-nst ...
@timer 1: 1.65875
ParsePAG info: 
-------------------------------------------------
1555529 & 31577 & 1046977 & 16678 & 49065 \\
	[DONE] 
the initial worklist size : 0
SCC and topological sorting ...
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
Propagation time       : 25.2172 s.
Propagation iterations : 18
Points-to size         : 128040305
Points-to set time     : 0.699893 s.
Total time             : 29.1376 s.
Peak memory            : 1928.9 MB.
Parsing SPARK's PAG file spark-dacapo/jre16/hsqldb-pag-nst ...
@timer 1: 1.42978
ParsePAG info: 
-------------------------------------------------
1329342 & 25377 & 900320 & 14690 & 46948 \\
	[DONE] 
the initial worklist size : 0
SCC and topological sorting ...
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
Propagation time       : 23.3055 s.
Propagation iterations : 18
Points-to size         : 107434532
Points-to set time     : 0.410937 s.
Total time             : 26.505 s.
Peak memory            : 1702.39 MB.
Parsing SPARK's PAG file spark-dacapo/jre16/jython-pag-nst ...
@timer 1: 1.73574
ParsePAG info: 
-------------------------------------------------
1664728 & 26413 & 1202110 & 14523 & 46044 \\
	[DONE] 
the initial worklist size : 0
SCC and topological sorting ...
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
Propagation time       : 28.8866 s.
Propagation iterations : 18
Points-to size         : 127367872
Points-to set time     : 0.452931 s.
Total time             : 32.726 s.
Peak memory            : 1899.55 MB.
Parsing SPARK's PAG file spark-dacapo/jre16/luindex-pag-nst ...
@timer 1: 0.509923
ParsePAG info: 
-------------------------------------------------
496187 & 11684 & 323121 & 5901 & 17388 \\
	[DONE] 
the initial worklist size : 0
SCC and topological sorting ...
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
Propagation time       : 4.12037 s.
Propagation iterations : 14
Points-to size         : 22943923
Points-to set time     : 0.116982 s.
Total time             : 5.11622 s.
Peak memory            : 548.121 MB.
Parsing SPARK's PAG file spark-dacapo/jre16/lusearch-pag-nst ...
@timer 1: 0.512922
ParsePAG info: 
-------------------------------------------------
496187 & 11684 & 323121 & 5901 & 17388 \\
	[DONE] 
the initial worklist size : 0
SCC and topological sorting ...
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
Propagation time       : 4.10838 s.
Propagation iterations : 14
Points-to size         : 22943928
Points-to set time     : 0.116982 s.
Total time             : 5.12022 s.
Peak memory            : 548.129 MB.
Parsing SPARK's PAG file spark-dacapo/jre16/pmd-pag-nst ...
@timer 1: 1.48077
ParsePAG info: 
-------------------------------------------------
1427514 & 25492 & 995545 & 13949 & 42979 \\
	[DONE] 
the initial worklist size : 0
SCC and topological sorting ...
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
Propagation time       : 20.6029 s.
Propagation iterations : 18
Points-to size         : 109845629
Points-to set time     : 0.420936 s.
Total time             : 23.9854 s.
Peak memory            : 1732.11 MB.
Parsing SPARK's PAG file spark-dacapo/jre16/xalan-pag-nst ...
@timer 1: 1.3308
ParsePAG info: 
-------------------------------------------------
1275913 & 25082 & 864071 & 14419 & 41527 \\
	[DONE] 
the initial worklist size : 0
SCC and topological sorting ...
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
propagating basic stuff ... 
propagating field sensitive stores ... 
propagating field sensitive loads ... 
-----------------------------------------------------------------------------
Propagation time       : 18.5002 s.
Propagation iterations : 18
Points-to size         : 97795369
Points-to set time     : 0.382942 s.
Total time             : 21.4737 s.
Peak memory            : 1614.89 MB.
